import "./features/pingGlide.js"
import "./features/etherwarp.js"
import "./features/blockhighlight.js"
import "./features/waypoints.js"
import "./features/struccheck.js"
import "./features/miningtracker"
import "./commands/help.js"
import "./features/efficiency.js"